<?php

declare(strict_types=1);

namespace Copy2Cloud\Base\Constants;

class ErrorCodes
{
    const UNKNOWN = 0;
    const MAINTENANCE_MODE = 1;
    const ENDPOINT_NOT_FOUND = 2;
    const INVALID_ROUTE_TYPE = 3;
    const INVALID_ARGUMENT = 4;
    const CRYPTO_INVALID_SECRET = 5;
    const CONTENT_ACCESS_DENIED_TO_MODIFY = 6;
    const CONTENT_ACCESS_DENIED_TO_UPDATE = 7;
    const CONTENT_ACCESS_DENIED_TO_DELETE = 8;
    const CONTENT_VALUE_MUST_BE_STRING = 9;
    const CONTENT_LENGTH_EXCEEDED = 10;
    const CONTENT_UNEXPECTED_EXPIRE_TIME = 11;
    const CONTENT_UNEXPECTED_TTL = 12;
    const CONTENT_INVALID_DESTROY_COUNT = 13;
    const CONTENT_INVALID_ACL_ALLOW_VALUE = 14;
    const CONTENT_INVALID_ACL_DENY_VALUE = 15;
    const CONTENT_CANNOT_ADD_OWN_IP_TO_DENY = 16;
    const CONTENT_NOT_FOUND = 16;
    const CONTENT_KEY_ALREADY_EXIST = 17;
    const CONTENT_KEY_MUST_BE_ALPHANUMERIC = 18;
}
